id = "codex-theme"
name = "Codex Theme"
version = "0.1.0"
schema_version = 1
authors = ["Marcus White <exponential.dev@gmail.com>"]
description = "Codex Theme"
repository = "https://github.com/exponential/codex"
